server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      filter:
        remove-hop-by-hop:
          headers:
            - dummy
      routes:
        - id: service-internal
          uri: lb://service-internal
          predicates:
            - Path=/service-internal/**
          filters:
            - StripPrefix=0
  security:
    user:
      name: deng
      password: 123456
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: /*
      base-path: /service-internal
