eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9006
spring:
  application:
    name: service-pay
  cloud:
    config:
      uri: http://localhost:8761/eureka/
        label: master


#    eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#    ##从配置中心读取文件
#    spring.cloud.config.discovery.enabled=true
#    ##配置中心的servieId，即服务名。
#    spring.cloud.config.discovery.serviceId=config-server
#    spring.cloud.config.label=master
#    spring.cloud.config.profile=dev
#
#
#    server.port=9001
#    spring.application.name=service-pay
