eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #是否将自己注册到eureka
    register-with-eureka: false
    #是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false

spring:
  cloud:
    config:
      label: master
      profile: dev
      server:
        native:
          searchPaths: D:/iammybest/configs/springcloud
