server:
  port: 9001

spring:
  application:
    name: config-server
  profiles:
    active: native
#TRACE < DEBUG < INFO < WARN < ERROR < FATAL
logging:
  level:
    root: info
    com.iammybest.springcloud.config: info
